import Head from "next/head";
import Banner from "@/common/components/header/Banner";
import Header from "@/common/components/header/Header";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Banner />
        <Header />
        {children}
      </>
    </>
  );
};

export default Layout;
